"""add property metadata fields

Revision ID: 14414e203c65
Revises: 5ec91a3e088c
Create Date: 2026-08-08 19:08:51.302916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14414e203c65'
down_revision: Union[str, Sequence[str], None] = '5ec91a3e088c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('properties', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('properties', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_column('properties', 'updated_at')
    op.drop_column('properties', 'created_at')
    op.drop_column('properties', 'status')
    # ### end Alembic commands ###
