"""add property ownership

Revision ID: 645d1a13052d
Revises: 5780dc128514
Create Date: 2026-08-11 20:17:02.310685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645d1a13052d'
down_revision: Union[str, Sequence[str], None] = '5780dc128514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'properties', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_column('properties', 'owner_id')
    # ### end Alembic commands ###
